name: vis_analytics
channels:
  # - nvidia
  - HuggingFace
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - accelerate
  - datasets
  - evaluate
  - matplotlib
  - numpy
  - pandas
  - python=3.11
  - pytorch
  # - pytorch-cuda
  - scikit-learn
  - seaborn
  - shap
  - spacy
  - spacy-model-en_core_web_sm
  - streamlit
  - torchaudio
  - torchvision
  - transformers
  - wordcloud
