name: vis_analytics
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - altair
  - arviz
  - bokeh
  - datapane
  - datasets
  - folium
  - lightgbm
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - plotly
  - plotnine
  - pytorch
  - scikit-learn
  - seaborn
  - shap
  - streamlit
  - torchaudio
  - torchvision
  - transformers
  - pytorch-cuda=12.1
