name: vis_analytics
channels:
  - defaults
dependencies:
  - altair
  - arviz
  - bokeh
  - datapane
  - folium
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - plotly
  - plotnine
  - python=3.11
  - scikit-learn
  - seaborn
  - streamlit
  - lightgbm
  - shap
